remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Dayana Castro Villa
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/evidencias-logica.appspot.com/o/WhatsApp%20Image%202023-09-14%20at%208.58.41%20PM.jpeg?alt=media&token=7619b348-02be-4d8e-ad94-c8f8fcdc0bcf

